### ISSUE TITLE
Question: do we want to be exposing e-mail addresses on the Person endpoint?

### ISSUE THREAD

**Issue by phillipadsmith** [BeautifulTrouble/beautifulrising-backends#8]
Do we want to be exposing e-mail addresses on the `person` endpoint? Perhaps that should only be for authenticated API requests, so that we know it's an internal or approved used of the information?

**Comment by adrian-the-git** [comment]
That was an oversight. I've removed them from the db but I'd like to implement some real filtering in the API server (the content loader is getting cluttered with little hacks that should really be fixed in docs but aren't). I'll leave this open for now.

**Comment by adrian-the-git** [comment]
API filtering is working now. In the CONFIG doc, add space-delimited key names to a key called "hidden:" under the relevant type.
